# frozen_string_literal: true
## Set a default host for urls generated by the DOI registrars (if necessary)
# Rails.application.routes.default_url_options[:host] = 'localhost:3000'
# Hyrax::Engine.routes.default_url_options[:host] = 'localhost:3000'

require 'hyrax/hirmeos/metrics_tracker'

Hyrax::Hirmeos::MetricsTracker.username = "Username"
Hyrax::Hirmeos::MetricsTracker.password = "secure_password"
Hyrax::Hirmeos::MetricsTracker.metrics_base_url = "https://metrics_base_url"
Hyrax::Hirmeos::MetricsTracker.translation_base_url = "https://translations_base_url"
Hyrax::Hirmeos::MetricsTracker.secret = ENV['HIRMEOS_TRANSLATOR_KEY']
